# Generated by Django 5.2.5 on 2025-09-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado')], default='D', max_length=1)),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP'), ('Discapacitado', 'Discapacitado')], default='Normal', max_length=20)),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('tipo_snapshot', models.CharField(default='Normal', max_length=20)),
                ('estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='estacionamientos.estacionamiento')),
            ],
        ),
    ]
