# Generated by Django 5.2.5 on 2025-09-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='patente',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estacionamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='estacionamientos.estacionamiento'),
        ),
    ]
