# Generated by Django 5.2.5 on 2025-09-09 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0002_remove_reserva_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='patente',
            field=models.CharField(default='DESCONOCIDA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estacionamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamientos.estacionamiento'),
        ),
    ]
