# Generated by Django 5.2.5 on 2025-09-09 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0003_reserva_fecha_inicio_reserva_fecha_termino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='patente',
            field=models.CharField(default='DESCONOCIDA', max_length=20),
        ),
    ]
