# Generated by Django 5.2.6 on 2025-09-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadEstacionamiento', models.IntegerField()),
                ('nombreSucursal', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=45)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='empresas.empresa')),
            ],
        ),
    ]
