# Generated by Django 5.2.6 on 2025-10-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='empresa',
        ),
    ]
