# Generated by Django 5.2.5 on 2025-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_sucursal_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
