# Generated by Django 5.1.4 on 2025-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('apellidoMaterno', models.CharField(max_length=45)),
                ('numeroTelefono', models.CharField(max_length=45)),
                ('rol', models.CharField(max_length=45)),
                ('discapacidad', models.BooleanField()),
            ],
        ),
    ]
