# Generated by Django 5.2.6 on 2025-10-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='discapacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado'), ('Cliente', 'Cliente')], default='Cliente', max_length=45),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
