# Generated by Django 5.2.5 on 2025-10-18 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado')], default='D', max_length=1)),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP'), ('Discapacitado', 'Discapacitado')], default='Normal', max_length=20)),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionamiento_id', models.IntegerField()),
                ('patente', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('es_reserva', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionamiento_id', models.IntegerField()),
                ('patente', models.CharField(default='DESCONOCIDA', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('tipo_snapshot', models.CharField(default='Normal', max_length=20)),
            ],
        ),
    ]
