# Generated by Django 5.2.6 on 2025-10-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0005_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='estacionamiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estacionamiento',
        ),
        migrations.AddField(
            model_name='historial',
            name='estacionamiento_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estacionamiento_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
